export const CONFLUENCE_TABLE_TEMPLATE = `<style>
      .slash-confluence-table-tool{box-sizing:border-box;width:100%;color:var(--vscode-editor-foreground);font-family:var(--vscode-font-family,sans-serif)}.slash-confluence-table-tool *{box-sizing:border-box}
      .ct-shell{overflow:hidden;border:1px solid var(--vscode-panel-border);border-radius:5px;background:var(--vscode-editor-background)}
      .ct-scroll{overflow:auto;max-height:620px;padding:8px}.ct-table{width:max-content;min-width:100%;border-spacing:0;border-collapse:separate;table-layout:auto}.ct-table td,.ct-table th{position:relative;width:auto;min-width:100px;padding:0;border-right:1px solid var(--vscode-panel-border);border-bottom:1px solid var(--vscode-panel-border);vertical-align:top}.ct-table tr:first-child>*{border-top:1px solid var(--vscode-panel-border)}.ct-table tr>*:first-child{border-left:1px solid var(--vscode-panel-border)}.ct-table th{background:var(--vscode-editorWidget-background)}
      .ct-cell{width:max-content;min-width:100%;min-height:36px;padding:8px;outline:0;white-space:pre;font-size:12px;line-height:1.35}.ct-cell:focus,.ct-cell.selected{box-shadow:inset 0 0 0 2px var(--vscode-focusBorder);background:color-mix(in srgb,var(--vscode-focusBorder) 8%,transparent)}.ct-cell.range-selected{color:var(--vscode-list-activeSelectionForeground,#fff);background:var(--vscode-list-activeSelectionBackground,var(--vscode-focusBorder));box-shadow:inset 0 0 0 1px var(--vscode-focusBorder)}.slash-confluence-table-tool.selecting,.slash-confluence-table-tool.selecting *{user-select:none}.ct-hint{margin-left:auto;color:var(--vscode-descriptionForeground);font-size:10px}.ct-column-resize{position:absolute;z-index:3;top:0;right:-4px;width:8px;height:100%;cursor:col-resize}.ct-row-resize{position:absolute;z-index:3;right:0;bottom:-4px;left:0;height:8px;cursor:row-resize}.ct-column-resize:hover,.ct-row-resize:hover{background:color-mix(in srgb,var(--vscode-focusBorder) 65%,transparent)}
      .ct-menu{position:fixed;z-index:1000;display:none;min-width:190px;padding:4px;border:1px solid var(--vscode-menu-border,var(--vscode-panel-border));border-radius:4px;background:var(--vscode-menu-background,var(--vscode-editorWidget-background));box-shadow:0 4px 14px rgba(0,0,0,.28)}.ct-menu.open{display:grid}.ct-menu button{padding:6px 9px;color:var(--vscode-menu-foreground,var(--vscode-foreground));border:0;border-radius:2px;background:transparent;text-align:left;cursor:pointer;font-size:11px}.ct-menu button:hover{background:var(--vscode-menu-selectionBackground,var(--vscode-list-hoverBackground));color:var(--vscode-menu-selectionForeground,var(--vscode-foreground))}.ct-menu button.active::before{content:'✓';display:inline-block;width:16px}.ct-menu-separator{height:1px;margin:3px 0;background:var(--vscode-menu-separatorBackground,var(--vscode-panel-border))}
    </style><div class="ct-shell"><div class="ct-scroll"><table class="ct-table"><colgroup></colgroup><tbody></tbody></table></div></div><div class="ct-menu" role="menu">
      <button type="button" data-action="paste">Вставить из буфера</button><span class="ct-menu-separator"></span><button type="button" data-action="row-above">Добавить строку выше</button><button type="button" data-action="row-below">Добавить строку ниже</button><button type="button" data-action="row-delete">Удалить строку</button><span class="ct-menu-separator"></span>
      <button type="button" data-action="column-left">Добавить столбец слева</button><button type="button" data-action="column-right">Добавить столбец справа</button><button type="button" data-action="column-delete">Удалить столбец</button><span class="ct-menu-separator"></span>
      <button type="button" data-action="header-row">Заголовочная строка</button><button type="button" data-action="header-column">Заголовочный столбец</button>
    </div>`;
