import type { LanguageFn } from 'highlight.js';

const KEYWORDS = [
  'abstract',
  'activate',
  'actor',
  'agent',
  'alt',
  'annotation',
  'archimate',
  'artifact',
  'as',
  'autonumber',
  'backward',
  'boundary',
  'box',
  'break',
  'caption',
  'card',
  'class',
  'cloud',
  'collections',
  'component',
  'control',
  'create',
  'critical',
  'database',
  'deactivate',
  'destroy',
  'else',
  'elseif',
  'end',
  'endbox',
  'endif',
  'endwhile',
  'entity',
  'enum',
  'file',
  'folder',
  'footer',
  'fork',
  'frame',
  'group',
  'header',
  'hide',
  'if',
  'interface',
  'is',
  'json',
  'legend',
  'loop',
  'map',
  'namespace',
  'newpage',
  'node',
  'note',
  'object',
  'of',
  'on',
  'opt',
  'package',
  'par',
  'participant',
  'partition',
  'person',
  'queue',
  'rectangle',
  'remove',
  'repeat',
  'restore',
  'return',
  'show',
  'skinparam',
  'split',
  'stack',
  'start',
  'state',
  'stop',
  'storage',
  'then',
  'title',
  'together',
  'usecase',
  'while',
].join(' ');

const plantUmlLanguage: LanguageFn = (hljs) => ({
  name: 'PlantUML',
  aliases: ['puml', 'iuml'],
  case_insensitive: true,
  keywords: {
    keyword: KEYWORDS,
    literal: 'true false null',
  },
  contains: [
    hljs.COMMENT(/\/'/, /'\//),
    hljs.COMMENT(/'/, /$/),
    {
      className: 'meta',
      begin: /^\s*@(?:start|end)[a-z0-9_]*/i,
      relevance: 10,
    },
    {
      className: 'meta',
      begin: /^\s*![a-z_]+/i,
      end: /$/,
    },
    hljs.QUOTE_STRING_MODE,
    {
      className: 'symbol',
      begin: /(?:<\|?|\*)?(?:--?|\.\.?|==?)+(?:\[[^\]\r\n]*\])?(?:--?|\.\.?|==?)*(?:\|?>|\*)?/,
      relevance: 1,
    },
    {
      className: 'variable',
      begin: /\$[a-z_][a-z0-9_]*/i,
    },
    {
      className: 'number',
      begin: /\b(?:0x[0-9a-f]+|\d+(?:\.\d+)?)\b/i,
      relevance: 0,
    },
    {
      className: 'string',
      begin: /#[a-z][a-z0-9_]*/i,
      relevance: 0,
    },
  ],
});

export default plantUmlLanguage;
